### ISSUE TITLE
Slider Not Working

### ISSUE THREAD

**Issue by briandconnolly** [ayhanavci/radiokayra#1]
The slider aside of the music channels is not functioning. Also, the dropdown only displays 3 stations.

I'm on Fedora 41.

Any suggestions would be greatly appreciated.

**Comment by ayhanavci** [comment]
The channel list should show up to 8 channels, any more than that you can still scroll down. And the volume slider seems to be working. I have just checked on my Fedora 41 and Ubuntu 24 machines. 
You could send me the logs by running the extension on terminal.  The command below should open a new shell and its logs will be printed on your terminal. If there is an error in the extension, it will display the relevant file name, line and error message.

```shell
dbus-run-session -- gnome-shell --nested --wayland
``` 
[Running a nested gnome shell](https://gjs.guide/extensions/development/debugging.html#running-a-nested-gnome-shell)

**Comment by ayhanavci** [comment]
It could be due to scaling issue from Display Settings, when it is not 100%. I'll look into it.

**Comment by briandconnolly** [comment]
1. So we are clear, it is not the volume slider.  It's the station slider. Also note, it only displays 3 channels.

2. There are no issues inside the nested shell.

**Comment by briandconnolly** [comment]
PS I believe you are correct. When I have my display at 100%, it works perfect.  The issue is when I run at 200% (which is my default use).

**Comment by ayhanavci** [comment]
I have Fedora 41 on 200% scale, Ubuntu on 100% scale both of which work fine as default. But I just checked OpenSuse tumbleweed and it acts up when it is not on 100%. That's how I caught it. It is just a matter of scaling. For now you can do this, open this file:

```shell
/home/ayhan/.local/share/gnome-shell/extensions/radiokayra@dokaton.com/constants.js
``` 

Just at the top, there are some numbers which you can play around. Set ```DEFAULT_PANEL_WIDTH``` ```PER_CHANNEL_PANEL_HEIGHT``` and ```MAX_PANEL_HEIGHT``` to larger numbers. For instance like this;
```
export const DEFAULT_PANEL_WIDTH = 600;
export const PER_CHANNEL_PANEL_HEIGHT = 80;
export const MAX_PANEL_HEIGHT = 1600;
```
It should look better when you logout and login.

**Comment by ayhanavci** [comment]
I am going to add some of the Constants into the Preferences so that users can modify from there, in case they want the extension bigger / smaller.  I'll see if there are any other issues and make an update in couple of weeks accordingly. Closing this issue for now.
